# Sidebar navigation

- label: 'Einführung'
  link: '/'
- label: 'Mitmachen'
  link: '/mitmachen'
- label: Regeln
  items:
    - label: 'Disc Golf'
      link: '/disc-golf/regeln'
    - label: 'Ultimate'
      link: '/ultimate/regeln'
    - label: 'Freestyle'
      link: '/freestyle/regeln'
    - label: 'Spirit of the game'
      link: '/spirit-of-the-game/regeln'
